//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnoss.ApiWrapper.EtiquetadoAutomaticoSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gnoss.com", ConfigurationName="EtiquetadoAutomaticoSOAP.EtiquetadoAutomaticoSoap")]
    public interface EtiquetadoAutomaticoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetasDesdeServicio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SeleccionarEtiquetasDesdeServicio(string titulo, string descripcion, string ProyectoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetasDesdeServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SeleccionarEtiquetasDesdeServicioAsync(string titulo, string descripcion, string ProyectoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SeleccionarEtiquetas(string titulo, string descripcion, string ProyectoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetas", ReplyAction="*")]
        System.Threading.Tasks.Task SeleccionarEtiquetasAsync(string titulo, string descripcion, string ProyectoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetasMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SeleccionarEtiquetasMultiple(string titulo, string descripcion, string ProyectoID, string identificadorPeticion, string fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gnoss.com/SeleccionarEtiquetasMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task SeleccionarEtiquetasMultipleAsync(string titulo, string descripcion, string ProyectoID, string identificadorPeticion, string fin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EtiquetadoAutomaticoSoapChannel : Gnoss.ApiWrapper.EtiquetadoAutomaticoSOAP.EtiquetadoAutomaticoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtiquetadoAutomaticoSoapClient : System.ServiceModel.ClientBase<Gnoss.ApiWrapper.EtiquetadoAutomaticoSOAP.EtiquetadoAutomaticoSoap>, Gnoss.ApiWrapper.EtiquetadoAutomaticoSOAP.EtiquetadoAutomaticoSoap {
        
        public EtiquetadoAutomaticoSoapClient() {
        }
        
        public EtiquetadoAutomaticoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtiquetadoAutomaticoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetadoAutomaticoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetadoAutomaticoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SeleccionarEtiquetasDesdeServicio(string titulo, string descripcion, string ProyectoID) {
            return base.Channel.SeleccionarEtiquetasDesdeServicio(titulo, descripcion, ProyectoID);
        }
        
        public System.Threading.Tasks.Task<string> SeleccionarEtiquetasDesdeServicioAsync(string titulo, string descripcion, string ProyectoID) {
            return base.Channel.SeleccionarEtiquetasDesdeServicioAsync(titulo, descripcion, ProyectoID);
        }
        
        public void SeleccionarEtiquetas(string titulo, string descripcion, string ProyectoID) {
            base.Channel.SeleccionarEtiquetas(titulo, descripcion, ProyectoID);
        }
        
        public System.Threading.Tasks.Task SeleccionarEtiquetasAsync(string titulo, string descripcion, string ProyectoID) {
            return base.Channel.SeleccionarEtiquetasAsync(titulo, descripcion, ProyectoID);
        }
        
        public void SeleccionarEtiquetasMultiple(string titulo, string descripcion, string ProyectoID, string identificadorPeticion, string fin) {
            base.Channel.SeleccionarEtiquetasMultiple(titulo, descripcion, ProyectoID, identificadorPeticion, fin);
        }
        
        public System.Threading.Tasks.Task SeleccionarEtiquetasMultipleAsync(string titulo, string descripcion, string ProyectoID, string identificadorPeticion, string fin) {
            return base.Channel.SeleccionarEtiquetasMultipleAsync(titulo, descripcion, ProyectoID, identificadorPeticion, fin);
        }
    }
}
